@echo off

REM ============================================================

REM  Clean script - remove everything generated by build.bat

REM

REM  Deletes (generated only):
REM    build\                                PyInstaller work dir
REM    msix_packaging\dist_msix\             MSIX output folder
REM    dist_zip\                             ZIP distribution output
REM    msix_packaging\app\OfficeSensitiveEncryptor.exe
REM    msix_packaging\app\README.txt         manual
REM    msix_packaging\app\LICENSE.txt        license
REM    msix_packaging\app\word\              copied demo vocab/samples
REM    __pycache__\                          Python bytecode cache
REM
REM  Keeps (original files, never touched):
REM    office_sensitive_encryptor.py
REM    test_encryptor.py
REM    office_sensitive_encryptor.spec
REM    build.bat  clean.bat
REM    PACKAGING_GUIDE.txt
REM    word\  (source demo vocabularies + sample documents)
REM    msix_packaging\build_msix.bat
REM    msix_packaging\app\AppxManifest.xml
REM    msix_packaging\app\Assets\*  (all icon files)

REM ============================================================

cd /d "%~dp0"



set APP_DIR=msix_packaging\app



echo Cleaning build artifacts...



if exist "build" (

    rmdir /s /q "build"

    echo   removed build directory

)



if exist "msix_packaging\dist_msix" (
    rmdir /s /q "msix_packaging\dist_msix"
    echo   removed dist_msix directory
)

if exist "dist_zip" (
    rmdir /s /q "dist_zip"
    echo   removed dist_zip directory
)



if exist "%APP_DIR%\OfficeSensitiveEncryptor.exe" (

    del /q "%APP_DIR%\OfficeSensitiveEncryptor.exe"

    echo   removed exe

)



if exist "%APP_DIR%\*.txt" (
    del /q "%APP_DIR%\*.txt"
    echo   removed README.txt and LICENSE.txt
)

if exist "%APP_DIR%\word" (
    rmdir /s /q "%APP_DIR%\word"
    echo   removed copied word assets
)



if exist "__pycache__" (

    rmdir /s /q "__pycache__"

    echo   removed pycache directory

)



echo.

echo Clean complete. Original files were kept.

pause

